name: Docker
on:
  push:
    branches:
    - master
  # We want to monthly update the base image for security
  # TODO Can we avoid building the same image?
  schedule:
    # min hour dom month dow
    - cron: '42 3 2 * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - torch: '1.12.0'
          python: '3.9.13'
        - torch: '1.12.0'
          python: '3.9.13-slim'
        - torch: '1.12.1'
          python: '3.10.7'
        - torch: '1.12.1'
          python: '3.10.7-slim'
    steps:
    - id: created
      run: echo "::set-output name=created::$(date --utc +%Y-%m-%dT%H:%M:%SZ)"

    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # v2.0.0

    - name: Log in to Docker Hub
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # v2.0.0
      if: github.ref == 'refs/heads/master'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94 # v3.1.1
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/master' }}
        build-args: |
          CREATED=${{ steps.created.outputs.created }}
          SOURCE_COMMIT=${{ github.sha }}
          PYTHON=${{ matrix.python }}
          TORCH=${{ matrix.torch }}
          TORCH_REQUIREMENT=${{ matrix.url || format('torch=={0}', matrix.torch) }}
        # TODO add the latest tag, maybe somehow via docker/metadata-action
        tags: |
          okoko/python-torch:${{ matrix.torch }}-${{ matrix.python }}
        # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
        cache-from: type=gha,scope=${{ matrix.torch }}-${{ matrix.python }}
        cache-to: type=gha,scope=${{ matrix.torch }}-${{ matrix.python }},mode=max

  # Can not use Personal Access Token to update the README. Returns FORBIDDEN.
  describe:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@da890086d39c735e41d8823c8a95bde4302c3d64 # v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: okoko/python-torch
