# This requires
# vars.DOCKERHUB_USERNAME for the result image account
# secrets.DOCKERHUB_USERNAME for the account that pushes the image
# secrets.DOCKERHUB_TOKEN for the account password that pushes the image

name: Build Torchvision Wheel

on:
  workflow_dispatch:
    inputs:
        torchvision-version:
            description: 'Version of torchvision to build (e.g. 0.16.2)'
            required: true
            default: '0.16.2'
            type: string
        pytorch-version:
            description: 'Torch version (check compatibility matrix)'
            required: true
            default: '2.1.2'
            type: string
        push-to-registry:
            description: 'Push image to registry'
            required: true
            type: boolean
            default: true

jobs:
  build-torchvision-wheel:
    runs-on: ubuntu-latest
    steps:
    - name: Print Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"
  
    - id: created
      run: echo "created=$(date --utc +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    - name: Log in to Docker Hub
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      if: github.ref == 'refs/heads/main'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
      with:
        context: .
        file: ./torchvision-wheel.Dockerfile
        push: ${{ inputs.push-to-registry }}
        build-args: |
          TORCHVISION_VERSION=${{ inputs.torchvision-version }}
          TORCH_WHEEL_SOURCE=${{ vars.DOCKERHUB_USERNAME }}/torch-wheels:${{ inputs.pytorch-version }}
          PYTORCH_VERSION=${{ inputs.pytorch-version }}
        # TODO add the latest tag, maybe somehow via docker/metadata-action
        tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/torchvision-wheels:${{ inputs.torchvision-version }}
        # https://docs.docker.com/build/ci/github-actions/cache/
        cache-from: type=gha,scope=torch-wheel
        cache-to: type=gha,scope=torch-wheel,mode=max
        platforms: linux/amd64,linux/arm64


